// This file was generated by counterfeiter
package fake_service_adapter

import (
	"sync"

	"github.com/pivotal-cf/on-demand-service-broker-sdk/bosh"
	"github.com/pivotal-cf/on-demand-service-broker-sdk/serviceadapter"
)

type FakeDashboardUrlGenerator struct {
	DashboardUrlStub        func(instanceID string, plan serviceadapter.Plan, manifest bosh.BoshManifest) (serviceadapter.DashboardUrl, error)
	dashboardUrlMutex       sync.RWMutex
	dashboardUrlArgsForCall []struct {
		instanceID string
		plan       serviceadapter.Plan
		manifest   bosh.BoshManifest
	}
	dashboardUrlReturns struct {
		result1 serviceadapter.DashboardUrl
		result2 error
	}
}

func (fake *FakeDashboardUrlGenerator) DashboardUrl(instanceID string, plan serviceadapter.Plan, manifest bosh.BoshManifest) (serviceadapter.DashboardUrl, error) {
	fake.dashboardUrlMutex.Lock()
	fake.dashboardUrlArgsForCall = append(fake.dashboardUrlArgsForCall, struct {
		instanceID string
		plan       serviceadapter.Plan
		manifest   bosh.BoshManifest
	}{instanceID, plan, manifest})
	fake.dashboardUrlMutex.Unlock()
	if fake.DashboardUrlStub != nil {
		return fake.DashboardUrlStub(instanceID, plan, manifest)
	} else {
		return fake.dashboardUrlReturns.result1, fake.dashboardUrlReturns.result2
	}
}

func (fake *FakeDashboardUrlGenerator) DashboardUrlCallCount() int {
	fake.dashboardUrlMutex.RLock()
	defer fake.dashboardUrlMutex.RUnlock()
	return len(fake.dashboardUrlArgsForCall)
}

func (fake *FakeDashboardUrlGenerator) DashboardUrlArgsForCall(i int) (string, serviceadapter.Plan, bosh.BoshManifest) {
	fake.dashboardUrlMutex.RLock()
	defer fake.dashboardUrlMutex.RUnlock()
	return fake.dashboardUrlArgsForCall[i].instanceID, fake.dashboardUrlArgsForCall[i].plan, fake.dashboardUrlArgsForCall[i].manifest
}

func (fake *FakeDashboardUrlGenerator) DashboardUrlReturns(result1 serviceadapter.DashboardUrl, result2 error) {
	fake.DashboardUrlStub = nil
	fake.dashboardUrlReturns = struct {
		result1 serviceadapter.DashboardUrl
		result2 error
	}{result1, result2}
}

var _ serviceadapter.DashboardUrlGenerator = new(FakeDashboardUrlGenerator)
